In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings("ignore")

In [2]:
df=sns.load_dataset("iris")

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x=df.drop("species",axis=1)
y=df["species"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn=KNeighborsClassifier(n_neighbors=13)

In [10]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.score(X_test,y_test)

1.0

In [12]:
from sklearn.svm import SVC

In [13]:
model_svm=SVC(C= 10,kernel="linear",gamma="auto")

In [14]:
model_svm.fit(X_train,y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [15]:
model_svm.score( X_test,y_test)

1.0

In [16]:
#lets use the grid search cv with svm model

In [18]:
from sklearn.model_selection import RandomizedSearchCV

In [19]:
classifier= RandomizedSearchCV((model_svm),{
    "C":[1,10,20,30],
    "kernel":["rbf","linear"],
  },n_iter=4,cv=5,return_train_score=False)

In [21]:
classifier.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
                   n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [22]:
results=pd.DataFrame(classifier.cv_results_)

In [25]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009694,0.007147,0.007603,0.005144,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,3
1,0.001971,0.001789,0.003967,0.002468,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.005673,0.005696,0.000607,0.000808,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4
3,0.008147,0.006953,0.002086,0.002558,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [26]:
results[["param_C","param_kernel","mean_test_score"]]

   param_C param_kernel  mean_test_score
0       10       linear         0.973333
1       10          rbf         0.980000
2       30       linear         0.960000
3        1          rbf         0.980000

In [17]:
# now we use the grid search cv with KNN  model