In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=sns.load_dataset("titanic")

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
df.drop(['class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive'],axis=1,inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [7]:
#fill null value by mean
df['age'].fillna(df['age'].mean(),inplace=True)

In [8]:
#drop null row 
df.dropna(subset=['embarked'],inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sex']=le.fit_transform(df['sex'])

In [11]:
df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [12]:
df['embarked']=le.fit_transform(df['embarked'])

In [13]:
df=df.astype(int)

In [14]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler=StandardScaler()
numerical_col=["pclass","age","fare","embarked"]
df[numerical_col]=scaler.fit_transform(df[numerical_col])

In [17]:
x=df.drop(columns=['survived'],axis=1)
y=df['survived']

In [18]:
x.head()

     pclass  sex       age  sibsp  parch      fare  embarked  alone
0  0.825209    1 -0.578023      1      0 -0.496733  0.586840      0
1 -1.572211    0  0.655371      1      0  0.791539 -1.939555      0
2  0.825209    0 -0.269675      0      0 -0.496733  0.586840      1
3 -1.572211    0  0.424109      1      0  0.429213  0.586840      0
4  0.825209    1  0.424109      0      0 -0.476604  0.586840      1

In [19]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int32

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [31]:
from sklearn.svm import SVC

In [33]:
model=SVC(kernel='rbf')

In [34]:
model.fit(x_train,y_train)

SVC()

In [42]:
y_pred=model.predict(x_test)

In [38]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [39]:
accuracy_score(y_pred,y_test)

0.8202247191011236

In [40]:
confusion_matrix(y_pred,y_test)

array([[92, 15],
       [17, 54]], dtype=int64)

In [41]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85       107
           1       0.78      0.76      0.77        71

    accuracy                           0.82       178
   macro avg       0.81      0.81      0.81       178
weighted avg       0.82      0.82      0.82       178

In [ ]:
#accuracy of SVM is 82%